/**
 * Stable error-code sanitization shared between service-layer persistence
 * and webhook public-response / audit paths.
 *
 * The explicit whitelist is the ONLY set of codes that may appear in
 * persisted InvocationResult.error, trigger-log "error" fields, and
 * public HTTP response body error / errorCode properties.
 *
 * Every other NativeInvocationError message is mapped to a generic code.
 * Non-NativeInvocationError exceptions always produce 'invocation_failed'.
 */

export const SAFE_NATIVE_ERROR_CODES: ReadonlySet<string> = new Set([
  // Stable codes emitted deliberately by the constrained runtimes. Keep this
  // exact: prefix matching would let raw provider text masquerade as a code.
  'invocation_aborted',
  'managed_requirements_unsupported',
  'native_auth_helper_unsupported',
  'native_auth_invalid',
  'native_auth_isolation_unverified',
  'native_auth_missing',
  'native_bridge_isolation_unverified',
  'native_catalog_missing',
  'native_config_isolation_unproven',
  'native_feature_isolation_unproven',
  'native_final_ambiguous',
  'native_host_request_forbidden',
  'native_process_exited',
  'native_invocation_failed',
  'native_inference_failed',
  'native_inference_incomplete',
  'native_isolation_missing',
  'native_model_not_found',
  'native_multiple_responses',
  'native_output_limit',
  'native_owner_guard_unsupported',
  'native_owner_identity_unknown',
  'native_profile_unverified',
  'native_protocol_invalid',
  'native_reasoning_effort_unsupported',
  'native_runtime_unavailable',
  'native_spawn_failed',
  'native_thread_isolation_unproven',
  'native_tool_isolation_unproven',
  'native_tool_isolation_unverified',
  'native_transport_closed',
  'native_turn_identity_missing',
  'output_schema_mismatch',
  // Generic codes generated by InvocationService itself
  'invocation_failed',
  'cancelled',
  'deadline_exceeded',
  'interrupted_unknown_outcome',
]);

/** Stable codes the webhook proxy may surface in daemon HTTP responses. */
export const SAFE_DAEMON_ERROR_CODES: ReadonlySet<string> = new Set([
  // Daemon validation / capacity codes
  'invalid_invocation',
  'idempotency_conflict',
  'invocation_capacity_exceeded',
  'invalid_request_id',
  // Proxy-layer errors
  'unexpected_response_format',
  'invocation_failed',
  'invocation_proxy_error',
  'invocation_timeout',
  'invocation_poll_error',
  'invocation_poll_timeout',
]);

/**
 * Sanitize a NativeInvocationError message for persistence.
 *
 * Only codes in {@link SAFE_NATIVE_ERROR_CODES} pass through unchanged.
 * Everything else is replaced with 'native_inference_failed' so that
 * callers cannot inject arbitrary text (paths, API keys, CLI stderr)
 * into the persisted error field.
 */
export function sanitizeNativeError(msg: string): string {
  if (SAFE_NATIVE_ERROR_CODES.has(msg)) return msg;
  return 'native_inference_failed';
}

/**
 * Sanitize a daemon HTTP error string for public webhook responses.
 *
 * Codes in {@link SAFE_DAEMON_ERROR_CODES} pass through; all others are
 * replaced with 'invocation_failed'.
 */
export function sanitizeDaemonError(msg: string | undefined): string {
  if (!msg) return 'invocation_failed';
  if (SAFE_DAEMON_ERROR_CODES.has(msg)) return msg;
  return 'invocation_failed';
}
